name = "mafia-game-night"
compatibility_date = "2024-10-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "mafia-game-db"
database_id = "6c7a27b5-0b31-4b07-ad90-aa26be3fbf26"
